netsuite e2e setup and first test commit
fylein/fyle-netsuite-app pull request #156
Opened 2022-12-12 10:25 UTC by DhaaraniCIT

2022-12-12 10:32 UTC, ashwin1111 commented on cypress/e2e/journey/netsuite-journey.cy.ts
> +    cy.visit('https://example.cypress.io')
remove / comment this out

2022-12-12 10:32 UTC, ashwin1111 commented on cypress/e2e/micro_actions/auth/logout.cy.js
> +    cy.get('[data-cy="ns-login"]').contains('Fyle NetSuite Integration')
create a custom command for querying the data attribute, can check partner dashboard

2022-12-12 10:32 UTC, ashwin1111 commented on cypress/e2e/micro_actions/auth/logout.cy.js
> +    cy.visit('/auth/logout')
implementation is mismatched with the doc
![Screenshot 2022-12-12 at 3 58 58 PM](https://user-images.githubusercontent.com/37061471/207022898-6b490b40-31e5-4a4a-9f93-d2c0e6c20981.png)

2022-12-12 10:32 UTC, ashwin1111 commented on cypress/fixtures/example.json
> +  "name": "Using fixtures to represent data",
not needed, can remove it off

2022-12-12 10:32 UTC, ashwin1111 commented on cypress/support/commands.ts
> +        navigateToMappingPage(pageName: string): void;
few things would make sense only for new design apps. Please to remove all unrelated ones

2022-12-12 10:32 UTC, ashwin1111 commented on cypress/support/commands.ts
> +    setupInterceptor('GET', '/errors/', 'getErrors');
few things would make sense only for new design apps. Please to remove all unrelated ones

2022-12-12 10:32 UTC, ashwin1111 commented on package.json
> +    "cypress_open": "cypress open -b chrome --e2e --env coverage=false",
`cypress:open`, can remove 11th line

2022-12-12 10:32 UTC, ashwin1111 commented on src/app/app.module.ts
> +// import * as Sentry from '@sentry/angular';
remove all these lines

2022-12-12 10:32 UTC, ashwin1111 commented on src/main.ts
> +// if (environment.sentry_dsn) {
remove

2022-12-12 10:37 UTC, DhaaraniCIT commented on cypress/support/commands.ts
> +        navigateToMappingPage(pageName: string): void;
will remove them while working

2022-12-12 10:37 UTC, DhaaraniCIT commented on cypress/support/commands.ts
> +    setupInterceptor('GET', '/errors/', 'getErrors');
will remove them while working

2022-12-12 13:48 UTC, ashwin1111 commented on cypress/e2e/micro_actions/auth/logout.cy.js
> +    cy.visit('/auth/logout')
please login and logout from the dropdown. No one will use the URL or knows the URL. We'll need to write tests to simulate user actions.

2022-12-12 13:49 UTC, ashwin1111 commented on package.json
> +    "cypress_open": "cypress open -b chrome --e2e --env coverage=false",
`cypress:open` instead of `cypress_open`

2022-12-13 15:23 UTC, ashwin1111 requested changes

2022-12-13 15:23 UTC, ashwin1111 commented on cypress/support/commands.ts
> +  Cypress.Commands.add('importToFyle', (fieldOrder: number, enable: boolean, optionName: string = '') => {
same

2022-12-13 15:23 UTC, ashwin1111 commented on cypress/support/commands.ts
> +  Cypress.Commands.add('selectConfigurationField', (fieldOrder: number, optionName: string) => {
same

2022-12-14 07:37 UTC, DhaaraniCIT commented on cypress/support/commands.ts
> +  Cypress.Commands.add('navigateToModule', (pageName: string) => {
it is used in header e2e test

2022-12-14 08:31 UTC, DhaaraniCIT commented on cypress/e2e/micro_actions/auth/auth.cy.js
> +describe('auth module', () => {
added to the documentation

2022-12-14 09:31 UTC, merged