Exclude export netsuite UI
fylein/fyle-netsuite-app pull request #178
Opened 2023-01-13 06:39 UTC by anishfyle

2023-01-16 10:21 UTC, ashwin1111 requested changes

2023-01-16 10:21 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +    if (conditionField === 'claim_number') {
conditionField === 'claim_number' || conditionField === 'employee_email' || conditionField === 'report_title'

2023-01-16 10:21 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        this.skipExportForm.controls.value_1.reset();
most of the logic is same as `conditionFieldWatcher1`, please make a common function and reuse

2023-01-16 10:21 UTC, ashwin1111 commented on src/app/core/services/mappings.service.ts
> +  getSkipExportConditionField(): Observable<ExpenseField[]> {
getFyleCustomFields

2023-01-16 10:21 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        this.setConditionField(conditionValue);
directly assign value to `this.conditionField`

2023-01-16 10:21 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +    this.settingsService.getSkipExport(2).subscribe((skipExport) => {
remove 2 and add workspace id

2023-01-16 10:21 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +      this.data = skipExport.results[0];
assign to const

2023-01-16 10:21 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +      this.data1 = skipExport.results[1];
same

2023-01-16 10:21 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        ofType = 'SELECT';
don't we get this info from the API?

2023-01-16 10:21 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +  }
we'll need to implement isLoading

2023-01-17 00:03 UTC, anishfyle commented on src/app/core/models/general-setting.model.ts
> +    // skip_export?: string[];
have removed the commented code.

2023-01-17 00:50 UTC, anishfyle commented on src/app/core/models/skip-export-selected.model.ts
> +export type SkipExportSelected = {
- changed to ExpenseFilterResponse.

- file name changed from skip-export-selected.model.ts ->  **TO**  -> expense-filter-response.model.ts

- have changed imports and name in setting service.

2023-01-17 00:53 UTC, anishfyle commented on src/app/core/models/general-setting.model.ts
> +    // skip_export?: string[];
- sync-up

2023-01-17 00:53 UTC, anishfyle commented on src/app/core/models/skip-export-selected.model.ts
> +  results: [
- done ✅

2023-01-17 00:53 UTC, anishfyle commented on src/app/core/models/skip-export.model.ts
> +  values: Array<any>;
- done ✅

2023-01-17 00:53 UTC, anishfyle commented on src/app/core/models/skip-export.model.ts
> +  join_by: string;
- sync-up

2023-01-17 00:54 UTC, anishfyle commented on src/app/core/models/skip-export.model.ts
> +  rank: number;
- sync-up

2023-01-17 00:54 UTC, anishfyle commented on src/app/core/models/skip-export.model.ts
> +  operator: string;
- sync-up

2023-01-17 01:11 UTC, anishfyle commented on src/app/core/services/settings.service.ts
> +  getSkipExport(workspaceId: number): Observable<SkipExportSelected> {
- done ✅

2023-01-17 01:13 UTC, anishfyle commented on src/app/core/services/mappings.service.ts
> +  getSkipExportConditionField(): Observable<ExpenseField[]> {
- done

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +  addCondition() {
`updateAdditionalFilterVisibility()`

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +          this.addCondition();
`updateAdditionalFilterVisibility()`

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +    if (isCustomCondition && rank === 1) {
this function is called only when is_custom is true, so remove the arg off, not needed

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +    if (isCustomCondition && rank === 1) {
rank: number

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        {
assign the options to a global variable, and copy the value in this block

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        {
this.operatorFieldOptions2 = this.operatorFieldDefaultOptions.filter();

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +    return {
`return operatorList;`

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +          ? this.setCustomOperatorOptions(
do this in if else block

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        if (conditionArray.length > 1 && formOptions1.join_by != null) {
```
if (conditionArray.length) {
 // line 365-372

 if (conditionArray.length > 1) {
    // same option setting logics

    updateAdditionalFilterVisibility()
 }
}
```

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        const operatorSelected2 = formOptions2.operator === 'isnull' && formOptions2.values[0] === 'True' ?  'is_empty' : formOptions2.operator === 'isnull' && formOptions2.values[0] === 'False' ? 'i
`selectedOperator1`

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        const operatorSelected2 = formOptions2.operator === 'isnull' && formOptions2.values[0] === 'True' ?  'is_empty' : formOptions2.operator === 'isnull' && formOptions2.values[0] === 'False' ? 'i
```
        const condition1 = conditionArray.length > 0 ? conditionArray[0] : '';
        let operator1;
        if (condition1.operator === 'isnull') {
          if (condition1.values[0] === 'True') {
            operator1 = 'is_empty';
          } else {
            operator1 = 'is_not_empty';
          }
        } else {
          operator1 = condition1.operator;
        }
```

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +            conditionArray[0].type === 'DATE'
refactor similar to operator

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        this.getCustomConditions();
this block is not needed, API won't fail

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        const formOptions2 = responses[1].results[1];
remove

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        }
`this.resetFields(condition1, value1, conditionSelected);`

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +    this.skipExportForm.controls.condition1.valueChanges.subscribe(
```
resetFields(operator, value, conditionSelected) {
    this.skipExportForm.controls[operator].reset();
    this.skipExportForm.controls[value].reset();
    if (conditionSelected.is_custom === true) {
      this.setCustomOperatorOptions(conditionSelected.is_custom, 1);
    } else if (conditionSelected.is_custom === false) {
      this.operatorFieldOptions1 = this.setDefaultOperatorOptions(
        conditionSelected.field_name
      );
    }
  }

  ```

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +    this.skipExportForm.controls.condition1.valueChanges.subscribe(
if rank is 1 => set value to operatorFieldOptions1, else set value to operatorFieldOptions2

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +  remCondition() {
send true to false as arg to updateAdditionalFilterVisibility() and set value to boolean variables

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +  addCondition() {
`showAdditionalCondition: bool`

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        if (conditionArray.length > 1 && formOptions1.join_by != null) {
if (conditionArray.length) {
 // line 365-372

 if (conditionArray.length > 1) {
    // same option setting logics

    updateAdditionalFilterVisibility()
 }
}

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +            [Validators.required],
do this conditionally

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +            [Validators.required],
check qbo-app

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +    }
make a common function out of this, send everything needed as args

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        : null,
do it in a single line

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +        .subscribe((skipExport: SkipExport) => {});
remove this from here

2023-01-20 07:35 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/skip-export/skip-export.component.ts
> +      this.snackBar.open('Skip Export fields saved successfully');
check if 2nd row exist and send another API here

2023-02-02 08:08 UTC, ashwin1111 approved these changes

2023-02-02 08:28 UTC, merged