netsuite app redesign
fylein/fyle-netsuite-app pull request #5
Opened 2020-09-02 05:33 UTC by Sravanksk

Adding Screenshots for the changes which are different from QBO Design

![Screenshot 2020-09-02 at 10 55 22 AM](https://user-images.githubusercontent.com/30795376/91935643-c6907300-ed0b-11ea-8d90-51158f684407.png)
![Screenshot 2020-09-02 at 10 55 15 AM](https://user-images.githubusercontent.com/30795376/91935633-c1332880-ed0b-11ea-88c5-b98b05e9df1a.png)

2020-09-02 06:17 UTC, ashwin1111 commented on src/app/core/guard/workspaces.guard.ts
> +        if (error.status === 400 && error.error.message === 'NetSuite Credentials not found in this workspace') {
can you check if this is needed? onboarded flag takes care of this?

2020-09-02 06:20 UTC, ashwin1111 commented on src/app/core/models/netsuite-credentials.model.ts
> +  ns_token_secret: string
I think we'll not return ns_token_secret

2020-09-02 06:22 UTC, ashwin1111 commented on src/app/core/models/netsuite-credentials.model.ts
> +  ns_consumer_secret: string
I think we'll not return ns_token_secret

2020-09-02 06:23 UTC, ashwin1111 commented on src/app/core/models/netsuite-credentials.model.ts
> +  ns_token_secret: string
I think we'll not return ns_token_secret

2020-09-02 06:25 UTC, ashwin1111 commented on src/app/core/models/subsidiary-mapping.model.ts
> +
extra line

2020-09-02 06:26 UTC, ashwin1111 commented on src/app/core/models/task.model.ts
> +  credit_card_purchase: number;
do we have credit_card_purchase in netsuite?

2020-09-02 06:27 UTC, ashwin1111 commented on src/app/core/models/task.model.ts
> +  cheque: number;
do we have cheque in netsuite?

2020-09-02 06:29 UTC, ashwin1111 commented on src/app/core/services/auth.service.ts
> +    return this.storageService.get('access_token') != null;
can we maintain !== and === everywhere

2020-09-02 06:35 UTC, ashwin1111 commented on src/app/core/services/expense-reports.service.ts
> +})
\n

2020-09-02 06:44 UTC, ashwin1111 commented on src/app/core/services/mappings.service.ts
> +    const generalMappings = {
can we send generalMappings object from component and post directly?

2020-09-02 06:53 UTC, ashwin1111 commented on src/app/core/services/settings.service.ts
> +  connectNetSuite(workspaceId: number, nsAccountId: string, nsConsumerKey: string, nsConsumerSecret: string, nsTokenId: string, nsTokenSecret: string) {
same, can we pass whole obj?

2020-09-02 06:54 UTC, ashwin1111 commented on src/app/core/services/settings.service.ts
> +  // postSettings(workspaceId: number, nextRun: string, hours: number, scheduleEnabled: boolean) {
can we rm this if it is not necessary

2020-09-02 07:05 UTC, ashwin1111 commented on src/app/core/services/workspace.service.ts
> +  getWorkspaces(orgId): Observable<any> {
:string

2020-09-02 07:07 UTC, ashwin1111 commented on src/app/netsuite/expense-groups/expense-groups.component.ts
> +  settings;
:any

2020-09-02 16:14 UTC, ashwin1111 commented on src/app/netsuite/settings/configuration/configuration.component.ts
> +          value: 'EXPENSE REPORT'
do we store like this in db? EXPENSE REPORT

2020-09-02 16:16 UTC, ashwin1111 commented on src/app/netsuite/settings/connect-netsuite/connect-netsuite.component.ts
> +    if (that.state == 'SUBSIDIARY') {
===

2020-09-02 16:18 UTC, ashwin1111 commented on src/app/netsuite/settings/connect-netsuite/ns-connection/ns-connection.component.ts
> +      forkJoin(connectNetSuite).subscribe(responses => {
why fork join is required for a single api call?

2020-09-02 16:20 UTC, ashwin1111 commented on src/app/netsuite/settings/connect-netsuite/ns-subsidiary/ns-subsidiary.component.ts
> +    let subsidiaryId = this.subsidiaryForm.value.netsuiteSubsidiaries;
const

2020-09-02 16:21 UTC, ashwin1111 commented on src/app/netsuite/settings/connect-netsuite/ns-subsidiary/ns-subsidiary.component.ts
> +    let netsuiteSubsidiary = this.netsuiteSubsidiaries.filter(filteredSubsidiary => filteredSubsidiary.destination_id === subsidiaryId)[0];
const

2020-09-02 16:21 UTC, ashwin1111 commented on src/app/netsuite/settings/connect-netsuite/ns-subsidiary/ns-subsidiary.component.ts
> +    if (subsidiaryId != null) {
!subsidiaryId should work, please check and change

2020-09-02 16:22 UTC, ashwin1111 commented on src/app/netsuite/settings/connect-netsuite/ns-subsidiary/ns-subsidiary.component.ts
> +    if(this.subsidiaryIsValid){
if (

2020-09-02 16:27 UTC, ashwin1111 commented on src/app/netsuite/settings/employee-mappings/employee-mappings.component.ts
> +        if (onboarded === true) {
if (onboarded)

2020-09-02 16:28 UTC, ashwin1111 commented on src/app/netsuite/settings/fyle-callback/fyle-callback.component.html
> +<p>fyle-callback works!</p>
can we remove this?

2020-09-02 16:28 UTC, ashwin1111 commented on src/app/netsuite/settings/fyle-callback/fyle-callback.component.ts
> +  ngOnInit() {
why is this component req? since there is nothing happening here

2020-09-02 16:29 UTC, ashwin1111 commented on src/app/netsuite/settings/general-mappings/general-mappings.component.html
> +          <mat-select class="general-mappings--input" placeholder="Select default credit card account for card expenses imported from Fyl"
Fyl -> Fyle

2020-09-02 16:29 UTC, ashwin1111 commented on src/app/netsuite/settings/general-mappings/general-mappings.component.ts
> +    if (accountPayableAccountId != null) {
if (accountPayableAccountId)

2020-09-02 16:30 UTC, ashwin1111 commented on src/app/netsuite/settings/general-mappings/general-mappings.component.ts
> +    if (locationId === null) {
i (!locationId)

2020-09-02 16:30 UTC, ashwin1111 commented on src/app/netsuite/settings/general-mappings/general-mappings.component.ts
> +    if (accountPayableAccountId != null) {
can we use ? :  in all these if

2020-09-02 16:31 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-callback/netsuite-callback.component.html
> +<p>netsuite-callback works!</p>
rm

2020-09-02 16:32 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-callback/netsuite-callback.component.ts
> +  ngOnInit() {
is this component required?

2020-09-02 16:35 UTC, ashwin1111 commented on src/app/netsuite/settings/schedule/schedule.component.ts
> +      if (!newValue && oldValue !== newValue) {
&& that.settings

2020-09-02 16:40 UTC, ashwin1111 commented on src/environments/environment.ts
> +  // fyle_client_id: 'tpa8PygXJWI1g',
rm this

2020-09-02 16:41 UTC, ashwin1111 commented on src/environments/environment.ts
> +// APP_URL='https://netsuite.fyleappz.com'
clean up this file please :pray:

2020-09-02 16:44 UTC, ashwin1111 requested changes
some very very minor changes required

2020-09-03 07:25 UTC, ashwin1111 commented on src/app/core/services/workspace.service.ts
> +  getWorkspaces(orgId): Observable<string> {
hey this should not be a string

2020-09-03 07:25 UTC, ashwin1111 commented on src/app/core/services/workspace.service.ts
> +  getWorkspaces(orgId): Observable<string> {
this api would return a workspace object

2020-09-03 07:27 UTC, ashwin1111 approved these changes

2020-09-03 07:27 UTC, Sravanksk commented on src/app/core/services/workspace.service.ts
> +  getWorkspaces(orgId): Observable<string> {
yes have tested this will update this in the next commit

2020-09-03 07:28 UTC, ashwin1111 commented on src/app/core/services/workspace.service.ts
> +  getWorkspaces(orgId): Observable<string> {
(orgId: string): Observable<any>

2020-09-03 07:36 UTC, Shwetabhk commented
@Sravanksk Can you please post and updated screenshot of the Logo
Also the onboarding screen

2020-09-03 11:05 UTC, Sravanksk commented
@Shwetabhk here is the onboarding screenshot and netsuite-logo
Onboarding Screen - 

![Screenshot 2020-09-03 at 4 32 57 PM](https://user-images.githubusercontent.com/30795376/92107376-4b11ed00-ee03-11ea-9bee-e8b3e2f99f2c.png)


Updated NetSuite Logo - 

![bitmap-copy@2x](https://user-images.githubusercontent.com/30795376/92107383-4e0cdd80-ee03-11ea-8ff9-638a0d53558b.png)

2020-09-09 06:47 UTC, Shwetabhk approved these changes

2020-09-09 06:47 UTC, merged