Tax implementation In Netsuite
fylein/fyle-netsuite-app pull request #98
Opened 2021-09-15 09:23 UTC by NileshPant1999

2021-09-15 09:59 UTC, Shwetabhk approved these changes

2021-09-15 11:37 UTC, ashwin1111 requested changes

2021-09-15 11:37 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/configuration/configuration.component.html
> +        <div class="schedule--toggle-text">Import Netsuite Tax Details to Fyle</div>
NetSuite

2021-09-15 11:37 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/expense-field-configuration/expense-field-configuration.component.ts
> +      setting => setting.source_field !== 'EMPLOYEE' && setting.source_field !== 'CATEGORY' && setting.source_field !== 'TAX_GROUP'
Add this in API

2021-09-27 05:22 UTC, ashwin1111 approved these changes

2021-09-27 05:22 UTC, ashwin1111 commented on src/app/core/models/general-setting.model.ts
> +    import_tax_items?: boolean;
? not needed

2021-09-27 05:22 UTC, ashwin1111 commented on src/app/netsuite/settings/netsuite-configurations/expense-field-configuration/expense-field-configuration.component.ts
> +      setting => setting.source_field !== 'EMPLOYEE' && setting.source_field !== 'CATEGORY' && setting.source_field !== 'TAX_GROUP'
this is not needed right?

2021-09-27 05:22 UTC, ashwin1111 commented on src/app/core/services/settings.service.ts
> +  postCountryDetails(): Observable<SubsidiaryMapping> {
Will suggest something here

2021-09-27 05:27 UTC, NileshPant1999 commented on src/app/netsuite/settings/netsuite-configurations/expense-field-configuration/expense-field-configuration.component.ts
> +      setting => setting.source_field !== 'EMPLOYEE' && setting.source_field !== 'CATEGORY' && setting.source_field !== 'TAX_GROUP'
yes

2021-09-27 06:20 UTC, Sravanksk approved these changes

2021-09-27 11:30 UTC, merged